
<MyTextInput@TextInput>
    markup: True
    hint_text: '%'
    multiline: False
    font_family: 'Roboto'
    font_size: '15sp'
    foreground_color: 64/255,64/255,64/255,1
    size_hint: 1, 1
    pos_hint: {'center_x': 0.5, 'center_y': 0.5}
    halign: 'center'
    padding_y: [self.height / 2.0 - (self.line_height / 2.0) * len(self._lines), 0]
    input_tipe: 'number'
    input_filter: 'float'


<MyAnchor>:
    Button:
        text: 'УДАЛИТЬ ЭЛЕМЕНТ'
        font_size: '10sp'
        background_color: 1,0,0,1
        size_hint: 0.8, 0.8
        pos_hint: {'x': 0.5, 'y': 0.5}
        on_release:
            app.Fourth.dell_component(root.instance)
            root.dad.dismiss()


<ResetButton>
    text: 'СБРОС'
    font_size: '20sp'
    pos_hint: {'center_x': 0.5, 'center_y': 0.5}
    on_press:
        app.Fourth.open_reset_popup()


<CalcButton>:
    text: 'РАССЧИТАТЬ'
    font_size: '20sp'
    on_release:
        app.Fourth.calculate()


<ButtonAddElement>:
    text: '+'
    size_hint: 1, 0.95
    on_release:
        root.add_element()


<Box>:
    orientation: 'vertical'

    MyChLabel:
        id: name_element

    MyTextInput:
        id: value_element
        on_text:
            root.change_value()


<Box2>:
    orientation: 'vertical'
    MyChLabel:
        id: name_element

    AnchorLayout:
        anchor_x: 'center'
        anchor_y: 'bottom'
        size_hint: 1, 1
        id: wid_id
        pos_hint: {'center_x': 0.5, 'center_y': 0.5}


<Box3>:
    orientation: 'vertical'

    MyChLabel:
        id: lab_1
        color: 64/255,64/255,64/255,1

    MyChLabel:
        id: lab_2
        color: 64/255,64/255,64/255,1


<BoxForElement>:
    size_hint: 1, 0.18
    on_touch_down:
        app.Fourth.open_component(self) if self.collide_point(*args[1].pos) else False


<AddComponent>:
    auto_dismiss: False
    size_hint: 0.8, 0.45
    title: 'Добавление нового компонента'

    BoxLayout:
        padding: 5
        spacing: 5
        orientation: 'vertical'

        Spinner:
            id: spinner_component
            markup: True
            size_hint: 0.9, 0.14
            pos_hint: {'center_x': 0.5, 'center_y': 0.5}
            font_size: '15sp'
            text: 'Выберите компонент'
            on_text:
                root.check_name()

        BoxLayout:
            id: box_grid
            size_hint: 1, 0.22
            spacing: 2

            GridLayout:
                id: grid_box
                rows: 2
                cols: 4
                pos_hint: {'center_x': 0.5, 'center_y': 0.5}

        BoxLayout:
            id: box_content
            orientation: 'vertical'
            spacing: 2
            size_hint: 1, 0.28

            Label:
                text: 'Процентное содержание\n    компонента в шихте'
                multiline: True

            MyTextInput:
                id: content_value
                size_hint: 0.3, 1

        Button:
            id: btn_add
            text: 'Добавить компонент в шихту'
            size_hint: 0.8, 0.14
            pos_hint: {'center_x': 0.5, 'center_y': 0.5}
            on_release:
                root.check_values()

        BoxLayout:
            id: box_id
            size_hint: 1, 0.14
            spacing: 5

            AnchorLayout:

                Button:
                    id: btn_id
                    text: 'ЗАКРЫТЬ'
                    font_size: '10sp'
                    background_color: 1,0,0,1
                    size_hint: 0.3, 0.8
                    pos_hint: {'x': 0.6, 'y': 0.5}
                    on_press:
                        root.close()
                        root.dismiss()


<AddComponents>:
    auto_dismiss: False
    size_hint: 0.9, 0.6
    title: 'Составление смеси'

    BoxLayout:
        spacing: 2
        orientation: 'vertical'

        BoxLayout:
            id: box_id
            size_hint: 1, 0.12
            spacing: 5

            Button:
                text: 'НАЗАД'
                font_size: '15sp'
                size_hint: 0.3, 0.8
                pos_hint: {'left_bottom': 0, 'center_y': 0.5}
                on_press:
                    root.close()
                    root.dismiss()

            Button:
                id: btn_id
                text: 'ЗАКРЫТЬ'
                font_size: '15sp'
                size_hint: 0.3, 0.8
                pos_hint: {'right_bottom': 1, 'center_y': 0.5}
                on_press:
                    root.close()
                    root.dismiss()

        Button:
            text: 'Добавить компонент'
            size_hint: 1, 0.12
            pos_hint: {'center_x': 0.5, 'center_y': 0.5}
            on_press:
                root.add_new_component()

        BoxForElement:
            id: first_box
            on_children:
                root.add_name()

        BoxForElement:
            id: second_box
            on_children:
                root.add_name()

        BoxForElement:
            id: third_box
            on_children:
                root.add_name()

        BoxLayout:
            id: box_result
            size_hint: 1, 0.12

        Button:
            text: 'Внести смесь в состав'
            size_hint: 1, 0.12
            pos_hint: {'center_x': 0.5, 'center_y': 0.5}
            on_press:
                root.add_mixture()
                root.dismiss()
