
<MyChLabel@Label>
    markup: True
    halign: 'center'
    valign: 'middle'
    font_size: '20sp'
    color: 1, 1, 1, 1


<MyTextInput@TextInput>
    markup: True
    hint_text: '%'
    multiline: False
    font_family: 'Roboto'
    font_size: '15sp'
    foreground_color: 64/255,64/255,64/255,1
    size_hint: 1, 1
    pos_hint: {'center_x': 0.5, 'center_y': 0.5}

    halign: 'center'
    padding_y: [self.height / 2.0 - (self.line_height / 2.0) * len(self._lines), 0]
    input_tipe: 'number'
    input_filter: 'float'


<ButtonAddElement>:
    text: '+'
    size_hint: 1, 0.95
#    pos_hint: {'center_x': 0.5, 'center_y': 0.5}
    on_release:
        root.add_element()


<Box>:
    orientation: 'vertical'

    MyChLabel:
        id: name_element

    MyTextInput:
        id: value_element


<Box2>:
    orientation: 'vertical'
    MyChLabel:
        id: name_element

    AnchorLayout:
        anchor_x: 'center'
        anchor_y: 'bottom'
        size_hint: 1, 1
        id: wid_id
        pos_hint: {'center_x': 0.5, 'center_y': 0.5}


<Box3>:
    orientation: 'vertical'

    MyChLabel:
        id:
    MyChLabel:
        id:


<AddComponent>:
    auto_dismiss: False
    size_hint: 0.8, 0.45
    title: 'Добавление нового компонента'

    BoxLayout:
        padding: 5
        spacing: 5
        orientation: 'vertical'

        BoxLayout:
            id: box_id
            size_hint: 1, 0.14
            spacing: 5

            Button:
                text: 'НАЗАД'
                font_size: '15sp'
                size_hint: 0.3, 0.8
                pos_hint: {'left_bottom': 0, 'center_y': 0.5}
                on_press:
                    root.close()
                    root.dismiss()

            Button:
                id: btn_id
                text: 'ЗАКРЫТЬ'
                font_size: '15sp'
                size_hint: 0.3, 0.8
                pos_hint: {'right_bottom': 1, 'center_y': 0.5}
                on_press:
                    root.close()
                    root.dismiss()

        Spinner:
            id: spinner_component
            size_hint: 0.8, 0.14
            pos_hint: {'center_x': 0.5, 'center_y': 0.5}
            font_size: '20sp'
            text: 'Выберите компонент'
            values: ['ПГНУ-2', 'ШАРО-40', 'ШМЖБ-2', 'ССП-1', 'ССП-9']
            on_text:
                root.clear_grid()
                root.build()

        BoxLayout:
            id: box_grid
            size_hint: 1, 0.22
            spacing: 2

            GridLayout:
                id: grid_box
                rows: 2
                cols: 4
                pos_hint: {'center_x': 0.5, 'center_y': 0.5}

        BoxLayout:
            id: box_content
            orientation: 'vertical'
            spacing: 2
            size_hint: 1, 0.28

            Label:
                text: 'Процентное содержание\n    компонента в шихте'
                multiline: True

            MyTextInput:
                id: content_value
                size_hint: 0.3, 1

        Button:
            id: btn_add
            text: 'Добавить компонент в шихту'
            size_hint: 0.8, 0.14
            pos_hint: {'center_x': 0.5, 'center_y': 0.5}
            on_release:
                root.add_component()
